index.html
style.css

Adding Final Project to repo.

---

index.html
style.css

Modify Dropdown Status in Task Form
Extra inline style: z-index:666; display: block;

Modify Dropdown Status in Task Form

---

index.html
style.css

Removing Display:None; from the Pop-up Form

Removing Display:None; from the Pop-up Form

---

index.html
pop-up.html
style.css

Added pop-up.html for Task Form to review

Added pop-up.html for form review

---

index.html
style.css

"editing col size and add media query"

editing col size and add media query

---

index.html
style.css

increasing form-size

---

index.html

replacing drop-down status with select status

replacing drop-down status with select status

---

index.html
style.css

Mainly for Color Changes, and modify header and section HTML tag names.

Mainly for Color Changes

---

style.css

resubmit style.css

---

index.html
style.css

Added Status Colors in both files

Added Status Colors in both files

---

index.html
index.js

adding validation codes

---

index.html
js/index.js
js/taskManager.js

Adding codes for task 5

---

index.html
js/index.js
js/taskManager.js

adding codes for task 6

---

js/index.js
js/taskManager.js

adding codes to clear Task form when CloseX is clicked

adding codes to clear Task form when CloseX is clicked

---

index.html
js/index.js
js/taskManager.js

adding codes for tak7 to display all cards in card layout form

adding codes for tak7 to display all cards in card layout form

---

index.html
js/index.js
js/taskManager.js
style.css

disable past date

---

index.html
js/index.js

modifying the validation rule

---

index.html
js/index.js
js/taskManager.js
style.css

adding delete button

---

index.html
js/index.js
js/taskManager.js

adding codes for mark as done button

adding codes for mark as done button

---

js/index.js
js/taskManager.js

cleaning up codes 

---

js/index.js
js/taskManager.js
style.css

modifying CreateHTML function to add code for hiding DONE button and also make some color changes.

modifying CreateHTML function to add code for hiding DONE button

---

index.html
js/taskManager.js
style.css

adding codes for setting size of the description field

adding codes for setting size of the description field

---

index.html
js/index.js

modifying validation rule of assigned name to accept up to 10 characters only

modifying validation rule of assigned name

---

js/index.js
js/taskManager.js
style.css

adding codes for tasks 9 and 10

adding codes for task 9 and 10

---

js/taskManager.js

adjusting color

---

.vscode/launch.json
index.html
style.css

adding back to top and hide edit button

adding back to top and hide edit button

---

index.html
style.css

adjusting position of the back-to-top button to fixed bottom

adjusting position of the back-to-top button to fixed bottom

---

style.css

adding animation codes for back-to-top button

adding animation codes for back-to-top button
